source 'https://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2','~>0.3.11'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'uuidtools'
gem 'carrierwave'
gem 'rscribd'
gem "recaptcha", :require => "recaptcha/rails"
gem "daemons"
gem 'delayed_job_active_record'
gem 'impressionist' ,:git => 'git://github.com/gauravtiwari5050/impressionist.git'
gem 'execjs'
gem 'therubyracer'
gem 'fog'
gem 'spreadsheet'
gem "validates_existence", ">= 0.4"
gem 'exception_notification'
gem 'tinymce-rails'
gem "jquery-ui-themes", "~> 0.0.4"
gem 'sunspot_rails'
gem 'sunspot_solr'
gem "nested_form", :git => 'https://github.com/ryanb/nested_form.git'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
